plugins {
    // Apply the spotless plugin before common.gradle.
    id 'com.diffplug.spotless' version '8.5.1' apply false
}

apply from: "${rootDir}/gradle/common.gradle"

jar {
    archiveBaseName.set('family-tree')
}

dependencies {
    api project(':components:neasaa-base-app')
    //implementation libraries.springFramework
    //implementation libraries.logger
	api libraries.ibmIcu4j
    testImplementation libraries.unitTest
}