package com.neasaa.familytree.operation;

public interface OperationNames {
	String ADD_FAMILY = "ADD_FAMILY";
	String SEARCH_FAMILY = "SEARCH_FAMILY";
	String UPDATE_FAMILY_ADDRESS = "UPDATE_FAMILY_ADDRESS";
	String GET_FAMILY_DETAILS = "GET_FAMILY_DETAILS";
	
	String ADD_FAMILY_MEMBER = "ADD_FAMILY_MEMBER";
	String GET_MEMBER_PROFILE = "GET_MEMBER_PROFILE";

	String MANAGE_RELATIONSHIP = "MANAGE_RELATIONSHIP";

	String GET_EVENTS = "GET_EVENTS";

	String GET_ACCOUNT_LIST = "GET_ACCOUNT_LIST";
	String GET_ACCOUNT_STATEMENT = "GET_ACCOUNT_STATEMENT";
}
