package com.neasaa.familytree.operation;

public interface OperationNames {
  String REGISTER_FAMILY = "REGISTER_FAMILY";
  String GET_FAMILY_REGISTRATION_REQUESTS = "GET_FAMILY_REGISTRATION_REQUESTS";
  String PROCESS_FAMILY_REGISTRATION = "PROCESS_FAMILY_REGISTRATION";
  String ADD_FAMILY = "ADD_FAMILY";
  String SEARCH_FAMILY = "SEARCH_FAMILY";
  String UPDATE_MY_FAMILY_DETAILS = "UPDATE_MY_FAMILY_DETAILS";
  String UPDATE_ANY_FAMILY_DETAILS = "UPDATE_ANY_FAMILY_DETAILS";
  String GET_FAMILY_DETAILS = "GET_FAMILY_DETAILS";
  String UPDATE_MY_FAMILY_IMAGE = "UPDATE_MY_FAMILY_IMAGE";
  String UPDATE_ANY_FAMILY_IMAGE = "UPDATE_ANY_FAMILY_IMAGE";

  String ADD_MEMBER_TO_MY_FAMILY = "ADD_MEMBER_TO_MY_FAMILY";
  String ADD_MEMBER_TO_ANY_FAMILY = "ADD_MEMBER_TO_ANY_FAMILY";
  String GET_MEMBER_PROFILE = "GET_MEMBER_PROFILE";
  String UPDATE_MY_FAMILY_MEMBER = "UPDATE_MY_FAMILY_MEMBER";
  String UPDATE_ANY_FAMILY_MEMBER = "UPDATE_ANY_FAMILY_MEMBER";
  String UPDATE_MY_FAMILY_MEMBER_IMAGE = "UPDATE_MY_FAMILY_MEMBER_IMAGE";
  String SEARCH_FAMILY_MEMBER = "SEARCH_FAMILY_MEMBER";

  String MANAGE_RELATIONSHIP = "MANAGE_RELATIONSHIP";

  String GET_EVENTS = "GET_EVENTS";

  String GET_ACCOUNT_LIST = "GET_ACCOUNT_LIST";
  String GET_ACCOUNT_STATEMENT = "GET_ACCOUNT_STATEMENT";

  String GET_SAMAJ_STATISTICS = "GET_SAMAJ_STATISTICS";

  String WHO_AM_I = "WHO_AM_I";
}
