plugins {
    // Apply the spotless plugin before common.gradle.
    id 'com.diffplug.spotless' version '8.5.1' apply false
}

apply from: "${rootDir}/gradle/common.gradle"

dependencies {
    api libraries.log4j
    testImplementation libraries.integTest
    testImplementation libraries.jackson
    testImplementation libraries.excel
    testImplementation libraries.neasaaUtils
}
