plugins {
    // Apply the spotless plugin before common.gradle.
    id 'com.diffplug.spotless' version '8.5.1' apply false
}

apply from: "${rootDir}/gradle/common.gradle"

jar {
    archiveBaseName.set('family-tree-ops-tool')
    enabled = true
}

dependencies {
    implementation project(':components:family-tree')
    implementation libraries.excel
}

task runOpsTool(type: JavaExec) {
    group = 'application'
    description = 'Run Ops Tool'
    mainClass = 'com.neasaa.familytree.OpsTool'
    classpath = sourceSets.main.runtimeClasspath +
                files('src/main/config/')
    jvmArgs = ['-Xmx512m']                               // optional JVM args
    // args = [project.hasProperty('excelFile') ? project.property('excelFile') : '']
    // doFirst {
    //     println "Classpath:"
    //     classpath.each { println it }
    // }
}