jar {
    archiveBaseName.set('family-tree-web-boot')
    enabled = true
}

dependencies {
    implementation project(':components:family-tree')
    implementation project(':components:neasaa-base-app')
    implementation (libraries.springBoot)
    //exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    implementation libraries.springFrameworkWeb
    implementation libraries.springFramework
    implementation libraries.jackson
    implementation libraries.userAgentParser
    implementation libraries.prefixmap
}

apply plugin: 'eclipse-wtp'

// Define frontend path (absolute path preferred)
// Override uxDir path as 
// ./gradlew build -PfrontendPath=/Users/vijay/projects/family-tree-ux
def uxDir = project.findProperty("frontendPath") ?: "/Users/vijaygarothaya/work/product/chippaSamaj/family-tree-ux"
def uxBuildDir = "${uxDir}/build"

// Explicitly Build UX component using following command
// ./gradlew build -PbuildReactApp
def buildUxComponent = project.hasProperty("buildReactApp")

def resourcesDir = "$projectDir/src/main/resources"
def distributionDir = "${rootDir}/distribution"

task buildUx(type: Exec) {
    onlyIf { buildUxComponent }
    workingDir uxDir
    commandLine 'npm', 'run', 'rebuild'
    doFirst {
        println "Building UX files $uxDir :build"
    }
}

task copyUxFilesToBoot (type: Copy) {
    onlyIf { buildUxComponent }
    dependsOn buildUx
    from("$uxBuildDir")                     // React build output
    into("$resourcesDir/static")        // Spring Boot static resources

    doFirst {
        println "🔍 Copying UX files from: $uxBuildDir"
        println "📂 Destination: $resourcesDir/static"
        def destDir = file("$resourcesDir/static")
        if (destDir.exists()) {
            println "🗑️ Deleting existing static directory before copy"
            destDir.deleteDir()
        }
    }

    doLast {
        println "✅ Copy complete. Files in static folder:"
        println fileTree("$resourcesDir/static").files
    }
}

processResources.dependsOn copyUxFilesToBoot

task runApp(type: JavaExec) {
    group = 'application'
    description = 'Start Springboot Application'
    environment 'DB_PASSWORD_ENCRYPTION_SALT_KEY', 'secret-key'
    environment 'app.properties.file.name', 'rajput.properties'
    classpath = sourceSets.main.runtimeClasspath +
                files('src/main/config/')
    mainClass = 'com.neasaa.familytree.FamilyTreeApplication'
    //args = ['--spring.profiles.active=dev']             // optional args
    jvmArgs = ['-Xmx512m']                               // optional JVM args

    doFirst {
        println "Classpath:"
        classpath.each { println it }
    }
}

eclipse {
    def repoSource = "${rootDir.path}"
    // Fix windows directory delimiters
    repoSource = repoSource.replaceAll( "\\\\", "/" )

    project {
        name = 'family-tree-web-boot'
    }
    wtp.facet {
    	facet name:'org.eclipse.wst.common.project.facet.core.nature'
    }
}

// Task to copy app jar + dependency jars
// ./gradlew clean buildDist -PbuildReactApp
tasks.register('buildDist', Copy) {
    dependsOn jar // ensure app jar is built
    from(jar) {
        into 'lib'
    }
    from(configurations.runtimeClasspath) {
        into 'lib'
    }

    into "${distributionDir}"  // target location in project
}


task extraCleanup(type: Delete) {
    doFirst {
        println "🔍 Deleting: $distributionDir"
    }
    delete distributionDir
}

clean.dependsOn(extraCleanup)