plugins {
  	id 'com.diffplug.spotless' version '8.5.1'
}


// Common for all project define here
allprojects {
	

	task printJars {
		doLast {
			configurations.runtimeClasspath.resolvedConfiguration.resolvedArtifacts.each { artifact ->
				println artifact.file
			}
		}
	}
	

	// compileJava.dependsOn(checkVersion)
}